import {LayoutMain} from 'components';
import LayoutHeader from './LayoutHeader';
import Head from 'next/head';
import React from 'react';

const Layout = (props: React.PropsWithChildren): JSX.Element => {
  const {children} = props;

  return (
    <React.Fragment>
      <Head>
        <title>TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutHeader />

      <LayoutMain>
        {children}
      </LayoutMain>
    </React.Fragment>
  );
};

export default Layout;
